### PR TITLE
autoexec: fixed --check option

### PR DESCRIPTION
**Pull request by bagnacauda**
Fixed --check, the wrong variable was being used.

### CODE REVIEW

**Comment by terminalforlife** [comment]
Can you clarify that it fixes something? Because I haven't had any issues with the checking feature. I just now tested `--check` with `#!/usr/bin/env bash` and `#!/bin/bash` shebangs, but both seemed to work fine. I'm a bit confused as to what this commit fixes.

**Comment by terminalforlife** [comment]
I couldn't accept the PR, because it's quite an aggressive change, without going to the source of the problem, that being how the `case` statement was checking for valid shells.

I'm very grateful you brought the bug to my attention. Please do let me know, via Issue or PR, of any other problems I've overlooked. I can only do so much on my own, so it really helps a ton. If this isn't fixed like I think, be sure to let me know.

**Comment by bagnacauda** [comment]
Yes you are right, I didn't notice that the Exec is used again later in the script. I ran shellcheck, and noticed that SheBangBase is unused, that's why I assumed that.

I'm not sure of why you say it would have broke it, do /usr/bin/env bash and /bin/bash behave differently, or is it something else?

I'll let you know for sure of any other bugs I may find, thank you.

**Comment by bagnacauda** [comment]
Now I see, I should have put a little more thought into this, thank you for the explanation.

**Comment by terminalforlife** [comment]
It's OK. Even though it didn't go to plan, the result was a positive one. Because of you, a bug was fixed. :)

**Pull request closed without merging**
